-- erch: personal notes vimwiki config
-- Generated by erch wiki notes init. Do not edit — this file is managed.
-- Override at ~/.config/nvim/lua/user/vimwiki.lua

vim.g.vimwiki_list = {
  {
    path = '~/wiki/notes/',
    syntax = 'markdown',
    ext = '.md',
    custom_wiki2html = '',
  },
}

vim.g.vimwiki_global_ext = 0

-- Pre-render to HTML on save (lightweight — just check for pandoc)
vim.api.nvim_create_autocmd("BufWritePost", {
  pattern = vim.fn.expand("~/wiki/notes/*.md"),
  callback = function()
    vim.system({ "erch", "wiki", "html", vim.fn.expand("%:p"), "-o", "/dev/null" })
  end,
  desc = "Pre-render note on save via erch wiki html",
})
