general {
    lock_cmd = erch-system-lock                         # lock screen and 1password
    before_sleep_cmd = ERCH_LOCK_ONLY=true erch-system-lock    # lock before suspend without scheduling display off.
    after_sleep_cmd = sleep 1 && erch-system-wake                 # delay for PAM readiness, then turn on display.
    inhibit_sleep = 3                                      # wait until screen is locked
}

# Start screensaver after 2.5 minutes
listener {
    timeout = 150
    on-timeout = pidof hyprlock || erch-launch-screensaver
}

# Lock system after 5 minutes (screensaver resets idle timer, so have to just do half + 2s margin)
listener {
    timeout = 152
    on-timeout = erch-system-lock
    on-resume = erch-system-wake
}
